language: php

matrix:
  include:
  - php: 7.0
  - php: 7.1

sudo: false
cache:
  directories:
  - vendor
  - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini

install:
  - composer install

script:
  - >
    echo;
    echo "Linting all PHP files";
    find Classes/ Tests/ -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l;

  - >
    echo;
    echo "Running the integration tests";
    vendor/bin/phpunit -c Configuration/PHPUnit/phpunit.xml Tests/Integration/;

  - >
    echo;
    echo "Running the static analysis";
    vendor/bin/phpstan analyse -l 5 Classes/ Tests/;

  - >
    echo;
    echo "Running PHPMD";
    vendor/bin/phpmd Classes/ text vendor/phplist/phplist4-core/Configuration/PHPMD/rules.xml;

  - >
    echo;
    echo "Running PHP_CodeSniffer";
    vendor/bin/phpcs --standard=vendor/phplist/phplist4-core/Configuration/PhpCodeSniffer/ Classes/ Tests/;
